name: Daily Rebuild from latest nginx Docker image

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build-and-push:
    strategy:
      matrix:
        build-type: ["release", "debug"]
        with-openssl: ["true", "false"]

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Determine Docker tag
        id: docker-tag
        env:
          BUILD_TYPE: ${{ matrix.build-type }}
          WITH_OPENSSL: ${{ matrix.with-openssl }}
        run: |
          TAG="alpine"
          if [ "$WITH_OPENSSL" = "true" ]; then
            TAG="$TAG-openssl";
          fi
          if [ "$BUILD_TYPE" = "debug" ]; then
            TAG="$TAG-debug";
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: flecspublic.azurecr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_AUTH }}

      - name: Build and push (${{ matrix.build-type }})
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILD_TYPE=${{ matrix.build-type }}
            WITH_OPENSSL=${{ matrix.with-openssl }}
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: flecspublic.azurecr.io/docker/nginx:${{ steps.docker-tag.outputs.tag }}
          cache-from: type=gha,scope=buildkit-${{ steps.docker-tag.outputs.tag }}
          cache-to: type=gha,mode=max,scope=buildkit-${{ steps.docker-tag.outputs.tag }}
